---
driver:
  name: ec2
  aws_ssh_key_id: test-kitchen
  security_group_ids: ["<%= ENV['AWS_SECURITY_GROUP_ID'] %>"]
  region: "<%= ENV['AWS_REGION'] %>"
  subnet_id: "<%= ENV['AWS_SUBNET_ID'] %>"
  iam_profile_name: "<%= ENV['AWS_INSTANCE_PROFILE'] %>"
  instance_type: t2.micro
  tags:
    created-by: test-kitchen
    example-tag: example

transport:
  ssh_key: .test-kitchen.pem

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: rhel-6
  - name: rhel-7
  - name: centos-6
  - name: centos-7
  - name: fedora
  - name: amazon-linux
    source_ami:
      name: amzn-ami-hvm-*.x86_64-gp2
  - name: windows-2012r2
    source_ami:
      name: Windows_Server_2012_R2_RTM_English-64Bit-Base-*

suites:
  - name: default
    run_list:
      - recipe[ec2-tags-test::default]
    attributes:
