---
driver:
  name: ec2
  aws_ssh_key_id: test-kitchen
  security_group_ids: ["<%= ENV['AWS_SECURITY_GROUP_ID'] %>"]
  region: "<%= ENV['AWS_REGION'] %>"
  subnet_id: "<%= ENV['AWS_SUBNET_ID'] %>"
  instance_type: t2.micro
  tags:
    created-by: test-kitchen
    example-tag: example

transport:
  ssh_key: test-kitchen.pem

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[ec2-tags-test::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
